export const USERS_LOAD =  "USERS_LOAD";
export const USERS_LOAD_SUCCESS = 'USERS_LOAD_SUCCESS';
export const USERS_LOAD_FAIL = 'USERS_LOAD_FAIL';

export const SET_USER = 'SET_USER';
export const SAVE_USER = 'SAVE_USER';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';