export const USERS_LOAD =  "USERS_LOAD";
export const USERS_LOAD_SUCCESS = 'USERS_LOAD_SUCCESS';
export const USERS_LOAD_FAIL = 'USERS_LOAD_FAIL';

export const SET_USER = 'SET_USER';
export const SAVE_USER = 'SAVE_USER';
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS';
export const SAVE_USER_FINISHED = 'SAVE_USER_FINISHED';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const LOAD_POSTS = 'LOAD_POSTS';
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';
export const LOAD_POSTS_FINISHED = 'LOAD_POSTS_FINISHED';
export const LOAD_POSTS_FAILED = 'LOAD_POSTS_FAILED';

export const SAVE_POST = 'SAVE_POST';
export const SAVE_POST_SUCCESS = 'SAVE_POST_SUCCESS';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const UPDATE_POST_FINISHED = 'UPDATE_POST_FINISHED';
export const SAVE_POST_FAILED = 'SAVE_POST_FAILED';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FINISHED = 'DELETE_USER_FINISHED';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FINISHED = 'DELETE_POST_FINISHED';
export const DELETE_POST_FAILED = 'DELETE_POST_FAILED';

export const SET_POST = 'SET_POST';

export const SET_ACTIVE_USER = 'SET_ACTIVE_USER';